.TH MATRIXAPP 1 "2024-12-09" "1.0" "MatrixApp Manual"
.SH NAME
matrixapp \- пример программы для работы с матрицами
.SH SYNOPSIS
.B matrixapp
[\fIoptions\fR]
.SH DESCRIPTION
Программа \fBmatrixapp\fR предназначена для выполнения операций с матрицами, таких как сложение, умножение и транспонирование.

.SH OPTIONS
.TP
.B \-h, \--help
Показать справочную информацию по использованию программы.
.TP
.B \-v, \--version
Показать информацию о версии программы.

.SH EXAMPLES
.TP
Для того чтобы выполнить программу с параметром помощи:
.B matrixapp \-h
.TP
Для того чтобы проверить версию программы:
.B matrixapp \-v
.SH SEE ALSO
matrixlib(3), make(1)
.SH AUTHOR
Разработано группой студентов ПИ.
