name: Build, Test, and Generate Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test, and Generate Documentation
    runs-on: ubuntu-latest

    steps:
      # Проверить репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Установить необходимые зависимости
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake doxygen graphviz

      # Собрать проект
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      # Генерация документации
      - name: Generate documentation
        run: |
          doxygen Doxyfile

      # Создать ветку gh-pages (если не существует)
      - name: Create gh-pages branch (if not exists)
        run: |
          if ! git ls-remote --exit-code origin gh-pages; then
            git checkout --orphan gh-pages
            git reset --hard
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git commit --allow-empty -m "Initialize gh-pages branch"
            git push origin gh-pages
          fi

      # Развертывание документации на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
